### ISSUE TITLE
Issue with Internal Consistency Function

### ISSUE THREAD

**Issue by nikimaria87** [drsimonj/blogR#2]
When I try to run:
`inter_item <- d %>% correlate() %>% select(-rowname) %>% colMeans(na.rm = TRUE)`

I am receiving an error on R studio that reads:
**Correlation computed with
• Method: 'pearson'
• Missing treated using: 'pairwise.complete.obs'
Error in `select()`:
! Can't subset columns that don't exist.
✖ Column `rowname` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.**

Does anyone know how to fix this so I can execute the rest of the code listed on here?

**Comment by drsimonj** [comment]
Hi @nikimaria87! I've not been involved for a while but I believe a breaking change was made a few years back that changed `rowname` to `term`.

Best to check the latest docs/guidance over at https://github.com/tidymodels/corrr
